SCREEN_WIDTH = 1600;
SCREEN_HEIGHT = 900;
FULLSCREEN = false;

KEY_LEFT = "a";
KEY_RIGHT = "d";
KEY_UP = "w";
KEY_DOWN = "s";
KEY_RUN = "lshift";
KEY_QUIT = "escape";
KEY_PAUSE = "return";

KEY_LIGHT_UP = "up";
KEY_LIGHT_DOWN = "down";
KEY_LIGHT_LEFT = "left";
KEY_LIGHT_RIGHT = "right";

PLAYER_WIDTH = 20;
PLAYER_HEIGHT = 20;
PLAYER_WALK_SPEED = 100;
PLAYER_RUN_SPEED = 200;
PLAYER_INITIAL_DIMENSIONS = {
  x = 90,
  y = 40,
  w = PLAYER_WIDTH,
  h = PLAYER_HEIGHT
};

-- Debug Variables
DRAW_BOXES = true;